#!/bin/bash
set -a

if [ "$#" -ne 1 ]; then
  echo "Usage: ./BuildMeOnAurora <path to NEKRS_HOME>"
  echo -e "If okay with the default \$HOME/.local/nekrs, press ENTER to continue"
  echo "Or press Ctrl+C to quit"
  read -r -s KEY
  export NEKRS_HOME=$HOME/.local/nekrs
else
  export NEKRS_HOME=$1
fi

#... load the necessary modules here ...
module purge
module load release/2026  GCC/14.3.0 OpenMPI/5.0.8 CMake/4.0.3 Python/3.13.5

#...
if [ ! -d venv ] ; then
        python3 -m venv venv
	. venv/bin/activate
        python3 -m pip install --upgrade pip
        python3 -m pip install mpi4py
else
	. venv/bin/activate
fi


#... set the build and install directories
CWD=$PWD
echo -e "\033[35mInstalling nekRS at $NEKRS_HOME\033[m"
export INSTALL_DIR=$NEKRS_HOME
#...

#... set some environment variables
: ${ENABLE_SMARTREDIS:="ON"}
export CC=mpicc
export CXX=mpic++
export FC=mpif77
OCCA_CXX=g++
OCCA_CXXFLAGS="-O3"
export SYCL_ROOT=${CMPROOT}/linux
#...

#... build SmartRedis if enabled
if [ ${ENABLE_SMARTREDIS} == "ON" ]; then
  if [ -f "$NEKRS_HOME/SmartRedis/install/lib64/libsmartredis.so" ]; then
    echo -e "\033[35mFound SmartRedis at $NEKRS_HOME/SmartRedis/install/lib64/libsmartredis.so\033[m"
  else
    echo -e "\033[35mBuilding SmartRedis first ...\033[m"
    if [ ! -d "$NEKRS_HOME" ]; then
      mkdir -p $NEKRS_HOME
    fi
    cd $NEKRS_HOME
    git clone https://github.com/rickybalin/SmartRedis.git
    cd SmartRedis
    #pip install -e .
    make lib
    cd $CWD
    echo -e "\033[35mDone building SmartRedis\033[m"
    echo
  fi 
fi
#...

#... build nekRS
echo ""
if [ ${ENABLE_SMARTREDIS} == "ON" ]; then
  echo -e "\033[35mBuilding nekRS WITH SmartRedis ...\033[m"
  ./build.sh -DENABLE_SMARTREDIS=ON -DSMARTREDIS_INSTALL_DIR=$NEKRS_HOME/SmartRedis/install \
  -DMPI_HONOR_APPNUM=1 \
  -DHYPRE_CONFIGURE_FLAGS="--with-cxxstandard=14"

else
  echo -e "\033[35mBuilding nekRS WITHOUT SmartRedis ...\033[m"
  ./build.sh \
  -DMPI_HONOR_APPNUM=1 \
  -DHYPRE_CONFIGURE_FLAGS="--with-cxxstandard=14"
fi
#...

